services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - /.env
    restart: always
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: ["npm", "start"]
  
  
networks:
  app-network:
    driver: bridge

